name: Deploy MultiDocker2
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sgarmendia/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true sgarmendia/react-test npm run test
 
      - run: docker build -t sgarmendia/multi-client ./client
      - run: docker build -t sgarmendia/multi-nginx ./nginx
      - run: docker build -t sgarmendia/multi-server ./server
      - run: docker build -t sgarmendia/multi-worker ./worker
 
      - run: docker push sgarmendia/multi-client
      - run: docker push sgarmendia/multi-nginx
      - run: docker push sgarmendia/multi-server
      - run: docker push sgarmendia/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-887236268408
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
